apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-k8s
  template:
    metadata:
      labels:
        app: spring-k8s
    spec:
      volumes:
        - name: cache
          # node节点上的文件目录
          hostPath:
            path: /data/k8s
      initContainers: # 初始化
        - name: init-myservice
          image: jiangbo920827/spring-k8s:liveness
          volumeMounts: # 通过volume挂载
            - name: cache
              mountPath: /var/log/cache
          command: ["/bin/sh", "-c", "echo Hello from the initContainer handler > /var/log/cache/h.txt"]
      containers:
        - name: spring-k8s
          image: jiangbo920827/spring-k8s:liveness
          volumeMounts:
            - name: cache
              mountPath: /var/log/cache
          ports:
            - containerPort: 8080
