apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-hostpath
spec:
  minReadySeconds: 2 # Kubernetes在等待设置的时间后才进行升级
  strategy:
    # indicate which strategy we want for rolling update
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 # 升级过程中最多可以比原先设置多出的POD数量 比如 有4个replicas 这里会有1个Pending服务 总共1+4 = 5个pod
      maxUnavailable: 2 # 升级过程中最多有多少个POD处于无法提供服务的状态 同时最多会有2个terminating容器 注意这2个不属于上面5个
  replicas: 2
  selector:
    matchLabels:
      app: deploy-hostpath
  template:
    metadata:
      labels:
        app: deploy-hostpath
    spec:
      # 目录挂载 hostpath
      # 直接将node上的文件系统挂载到pod中,pod可以直接使用node中的文件
      # 只要节点目录没有异常 该节点上的pod无论状态如何 文件都在
      volumes:
        - name: cache
          # node节点上的文件目录
          hostPath:
            path: /data
      containers:
        - name: nginx
          image: nginx:1.7.8
          # 挂载目录
          volumeMounts:
            - name: cache
              # pod对应的目录
              mountPath: /var/log/cache
          ports:
            - containerPort: 80
