apiVersion: v1
kind: Service
metadata:
  name: service-node
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      nodePort: 30001
  selector:
    app: spring-k8s
  type: NodePort
  sessionAffinity: None
